#!/data/data/com.termux/files/usr/bin/bash
set -Eeuo pipefail

OWNER="${OWNER:-Ice1984m}"

ROOT="$HOME/mikis13-evolution-engine"
SITE="$HOME/.mikis13-evolution/site"

RESULT="$ROOT/state/latest-result.json"

FULL="$(
 jq -r '.prototype_repo // empty' \
 "$RESULT"
)"

[ -n "$FULL" ] || {
 echo "ℹ️ Geen prototype repo voor website."
 exit 0
}

TITLE="$(
 jq -r '.best_idea.title' \
 "$RESULT"
)"

SCORE="$(
 jq -r '.best_idea.score' \
 "$RESULT"
)"

SLUG="$(
 jq -r '.best_idea.slug' \
 "$RESULT"
)"

rm -rf "$SITE"

gh repo clone \
 "$OWNER/mikis13-site" \
 "$SITE"

cd "$SITE"

git checkout main

git pull --rebase origin main

BRANCH="bot/evolution-lab-$SLUG"

git checkout -b "$BRANCH"

export TITLE SCORE FULL SLUG

python <<'PY'
from pathlib import Path
import os

path = Path("index.html")

text = path.read_text(
    encoding="utf-8"
)

slug = os.environ["SLUG"]

marker = (
    f"evolution-lab:{slug}"
)

if marker in text:
    print("Website card bestaat al.")
    raise SystemExit(0)

title = os.environ["TITLE"]
score = os.environ["SCORE"]
repo = os.environ["FULL"]

card = f"""
      <!-- evolution-lab:{slug} -->
      <a class="card"
         href="https://github.com/{repo}"
         target="_blank"
         rel="noopener">
        <div class="icon">⚡</div>
        <div>
          <small>11 / EVOLUTION LAB</small>
          <h3>{title.upper()}</h3>
          <p>
            Automatisch ontdekt Mikis13 LAB-experiment.
            Blueprint score {score}/100.
            Onderzoek en ontwikkeling — nog geen afgewerkt product.
          </p>
        </div>
      </a>
"""

needle = """    </div>
  </section>

  <section class="human-os\""""

if needle not in text:
    print(
        "❌ Veilige invoegpositie niet gevonden."
    )
    raise SystemExit(1)

text = text.replace(
    needle,
    card + """    </div>
  </section>

  <section class="human-os\"""",
    1
)

path.write_text(
    text,
    encoding="utf-8"
)

print("✅ LAB card toegevoegd")
PY

git diff --check

git add index.html

if git diff --cached --quiet; then

  echo "ℹ️ Geen websitewijziging."
  exit 0

fi

git commit \
  -m "Add Evolution LAB prototype card"

git push \
  -u origin \
  "$BRANCH"

if gh pr list \
  --repo "$OWNER/mikis13-site" \
  --head "$BRANCH" \
  --state open \
  --json number \
  --jq 'length' |
  grep -q '^0$'
then

  gh pr create \
    --repo "$OWNER/mikis13-site" \
    --base main \
    --head "$BRANCH" \
    --title "Add $TITLE to Evolution LAB" \
    --body \
"Adds a truthful LAB-status project card generated by the Mikis13 Evolution Engine.

- Status: LAB
- Incubation score: $SCORE/100
- No claim that the project is production-ready.
- Website change is isolated in a bot PR."

fi

echo "✅ Website LAB PR klaar."
